[2024-05-11T15:29:55.860+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ademe_transform_data.transform_data_task manual__2024-05-11T15:24:50.122037+00:00 [queued]>
[2024-05-11T15:29:55.880+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ademe_transform_data.transform_data_task manual__2024-05-11T15:24:50.122037+00:00 [queued]>
[2024-05-11T15:29:55.880+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-05-11T15:29:55.918+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): transform_data_task> on 2024-05-11 15:24:50.122037+00:00
[2024-05-11T15:29:55.928+0000] {standard_task_runner.py:60} INFO - Started process 695 to run task
[2024-05-11T15:29:55.952+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ademe_transform_data', 'transform_data_task', 'manual__2024-05-11T15:24:50.122037+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/transform_dag.py', '--cfg-path', '/tmp/tmpbeglv5xx']
[2024-05-11T15:29:55.968+0000] {standard_task_runner.py:88} INFO - Job 100: Subtask transform_data_task
[2024-05-11T15:29:56.063+0000] {task_command.py:423} INFO - Running <TaskInstance: ademe_transform_data.transform_data_task manual__2024-05-11T15:24:50.122037+00:00 [running]> on host ced256f15635
[2024-05-11T15:29:56.225+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ademe_transform_data' AIRFLOW_CTX_TASK_ID='transform_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-11T15:24:50.122037+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-11T15:24:50.122037+00:00'
[2024-05-11T15:29:58.366+0000] {logging_mixin.py:188} INFO - Empty DataFrame
Columns: [n_dpe, etiquette_dpe, etiquette_ges, version_dpe, periode_construction, secteur_activite, type_energie_principale_chauffage, type_energie_n_1, type_usage_energie_n_1, surface_utile, conso_kwhep_m2_an, conso_e_finale_energie_n_1]
Index: []
[2024-05-11T15:29:58.370+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/transform_dag.py", line 46, in transform
    fp.data[["n_dpe", "payload"]].to_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3767, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 5877, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 5941, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['payload'] not in index"
[2024-05-11T15:29:58.381+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=ademe_transform_data, task_id=transform_data_task, execution_date=20240511T152450, start_date=20240511T152955, end_date=20240511T152958
[2024-05-11T15:29:58.619+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 100 for task transform_data_task ("['payload'] not in index"; 695)
[2024-05-11T15:29:58.653+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-11T15:29:58.676+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
